name: CI-CD Static Analysis, Testing, Docker Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  bash_lint:
    name: Bash Lint (ShellCheck)
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck deploy.sh

  yaml_lint:
    name: Run YamlLint
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run YamlLint
        run: yamllint config.yml

  python_unit_test:
    name: Run PyTest
    needs: [bash_lint, yaml_lint]
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run PyTest
        run: python3 -m pytest test_app.py

  docker_build:
    name: Docker Build and Push
    needs: python_unit_test
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/cicd-demo"
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.run_number }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.run_number }}

  deploy_to_test:
    name: Deploy to Target Server
    needs: docker_build
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_ACTOR, GITHUB_TOKEN
          script: |
            IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/cicd-demo"
            IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
            
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            sudo docker stop my-python-app || true
            sudo docker rm my-python-app || true
            sudo docker pull $IMAGE_NAME:latest
            sudo docker run -d --name my-python-app -p 80:3010 $IMAGE_NAME:latest
